version: '3.3'

services:
  
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./env/pgadmin.env
    #volumes:
    #  - pgadmin:/var/lib/pgadmin4
    ports:
      - "5050:80"
    restart: unless-stopped

  backend:
    build: ./backend/
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  postgres:
